language: node_js
node_js:
  - '5.9'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - 'npm install -g gulp'
script: gulp
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
