version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            PKG_VERSION=$(grep VERSION lib/version.rb | cut -d'"' -f2)
            if [[ "${CIRCLE_TAG}" != "v${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${CIRCLE_TAG}"
              echo "  PKG_VERSION: v${PKG_VERSION}"
              exit 1
            fi
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  update_package:
    jobs:
      - test:
          filters: *tagged_build_filters
      - publish:
          requires:
            - test
          filters: *tagged_build_filters
  test:
    jobs:
      - test:
          filters: *test_build_filters
